const CryptoJS = require("crypto-js");

const getCryptoConfig = () => {
  const secretKey = process.env.SECRET_KEY;
  const ivValue = process.env.IV;

  if (!secretKey || !ivValue) {
    throw new Error("As variáveis SECRET_KEY e IV são obrigatórias.");
  }

  return {
    iv: CryptoJS.enc.Utf8.parse(ivValue),
    key: CryptoJS.enc.Utf8.parse(secretKey),
  };
};

const encrypt = (content) => {
  const { iv, key } = getCryptoConfig();
  return CryptoJS.AES.encrypt(String(content ?? ""), key, {
    iv,
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7,
  }).toString();
};

const decrypt = (content) => {
  if (content === null || content === undefined || content === "") return "";
  try {
    const { iv, key } = getCryptoConfig();
    const bytes = CryptoJS.AES.decrypt(String(content), key, {
      iv,
      mode: CryptoJS.mode.CBC,
      padding: CryptoJS.pad.Pkcs7,
    });
    return bytes.toString(CryptoJS.enc.Utf8);
  } catch (error) {
    return "";
  }
};

const isEncryptedText = (value) => {
  if (value === null || value === undefined || value === "") return false;
  const decrypted = decrypt(value);
  if (!decrypted) return false;
  return encrypt(decrypted) === value;
};

const encryptIfNeeded = (value) => {
  if (value === null || value === undefined) return null;
  const text = String(value);
  if (!text) return "";
  return isEncryptedText(text) ? text : encrypt(text);
};

exports.up = async (pgm) => {
  pgm.sql("CREATE EXTENSION IF NOT EXISTS pgcrypto");

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS aux_unidade (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo text NOT NULL UNIQUE,
      label text NOT NULL,
      is_default boolean NOT NULL DEFAULT false,
      criado_em timestamp NOT NULL DEFAULT now(),
      atualizado_em timestamp NOT NULL DEFAULT now()
    )
  `);

  pgm.sql(`
    INSERT INTO aux_unidade (codigo, label, is_default)
    VALUES ('KG', 'Quilograma', true)
    ON CONFLICT (codigo)
    DO UPDATE SET label = EXCLUDED.label
  `);

  pgm.sql(`
    INSERT INTO aux_unidade (codigo, label, is_default)
    VALUES ('SACO', 'Saco', false)
    ON CONFLICT (codigo)
    DO UPDATE SET label = EXCLUDED.label
  `);

  pgm.sql(`
    CREATE UNIQUE INDEX IF NOT EXISTS aux_unidade_single_default
    ON aux_unidade (is_default)
    WHERE is_default = true
  `);

  pgm.sql(`
    WITH has_default AS (
      SELECT 1
      FROM aux_unidade
      WHERE is_default = true
      LIMIT 1
    )
    UPDATE aux_unidade
    SET is_default = true
    WHERE codigo = 'KG'
      AND NOT EXISTS (SELECT 1 FROM has_default)
  `);

  pgm.sql(`
    DO $$
    DECLARE
      kg_id integer;
      saco_id integer;
    BEGIN
      SELECT id INTO kg_id FROM aux_unidade WHERE codigo = 'KG' LIMIT 1;
      SELECT id INTO saco_id FROM aux_unidade WHERE codigo = 'SACO' LIMIT 1;

      IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'unidade_id'
      ) THEN
        ALTER TABLE insumos ADD COLUMN unidade_id integer;
      END IF;

      IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'estoque_minimo_unidade_id'
      ) THEN
        ALTER TABLE insumos ADD COLUMN estoque_minimo_unidade_id integer;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'unidade'
      ) THEN
        UPDATE insumos
        SET unidade_id = CASE
          WHEN lower(COALESCE(unidade, 'kg')) = 'saco' THEN saco_id
          ELSE kg_id
        END
        WHERE unidade_id IS NULL;
      ELSE
        UPDATE insumos
        SET unidade_id = kg_id
        WHERE unidade_id IS NULL;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'estoque_minimo_unidade'
      ) THEN
        UPDATE insumos
        SET estoque_minimo_unidade_id = CASE
          WHEN lower(COALESCE(estoque_minimo_unidade, 'kg')) = 'saco' THEN saco_id
          ELSE kg_id
        END
        WHERE estoque_minimo_unidade_id IS NULL;
      ELSE
        UPDATE insumos
        SET estoque_minimo_unidade_id = kg_id
        WHERE estoque_minimo_unidade_id IS NULL;
      END IF;

      IF kg_id IS NOT NULL THEN
        EXECUTE format('ALTER TABLE insumos ALTER COLUMN unidade_id SET DEFAULT %s', kg_id);
        EXECUTE format('ALTER TABLE insumos ALTER COLUMN estoque_minimo_unidade_id SET DEFAULT %s', kg_id);
      END IF;

      ALTER TABLE insumos ALTER COLUMN unidade_id SET NOT NULL;
      ALTER TABLE insumos ALTER COLUMN estoque_minimo_unidade_id SET NOT NULL;

      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'insumos_unidade_id_fkey'
      ) THEN
        ALTER TABLE insumos
        ADD CONSTRAINT insumos_unidade_id_fkey
        FOREIGN KEY (unidade_id)
        REFERENCES aux_unidade(id)
        ON DELETE RESTRICT;
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'insumos_estoque_minimo_unidade_id_fkey'
      ) THEN
        ALTER TABLE insumos
        ADD CONSTRAINT insumos_estoque_minimo_unidade_id_fkey
        FOREIGN KEY (estoque_minimo_unidade_id)
        REFERENCES aux_unidade(id)
        ON DELETE RESTRICT;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'unidade'
      ) THEN
        ALTER TABLE insumos DROP COLUMN unidade;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'estoque_minimo_unidade'
      ) THEN
        ALTER TABLE insumos DROP COLUMN estoque_minimo_unidade;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'tipo'
      ) THEN
        ALTER TABLE insumos DROP COLUMN tipo;
      END IF;

      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'insumos'
          AND column_name = 'preco_kg'
      ) THEN
        ALTER TABLE insumos DROP COLUMN preco_kg;
      END IF;
    END $$;
  `);

  pgm.sql(`
    UPDATE usuarios
    SET perfil = CASE WHEN perfil = 1 THEN 1 ELSE 2 END
  `);

  pgm.sql(`
    ALTER TABLE usuarios
    ALTER COLUMN perfil SET DEFAULT 2
  `);

  pgm.sql(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'usuarios_perfil_check'
      ) THEN
        ALTER TABLE usuarios
        ADD CONSTRAINT usuarios_perfil_check
        CHECK (perfil IN (1, 2));
      END IF;
    END $$;
  `);

  await pgm.db.query(`
    ALTER TABLE clientes
    ADD COLUMN IF NOT EXISTS protegido boolean NOT NULL DEFAULT false
  `);

  const nomeBalcao = "Cliente Balcão";
  const cpfBalcao = "487.123.220-40";
  const nomeBalcaoEnc = encryptIfNeeded(nomeBalcao);
  const cpfBalcaoEnc = encryptIfNeeded(cpfBalcao);
  const telefoneVazioEnc = encryptIfNeeded("");
  const enderecoVazioEnc = encryptIfNeeded("");

  const clientesResult = await pgm.db.query(
    "SELECT id, nome, cpf_cnpj FROM clientes",
  );

  const clienteBalcao = clientesResult.rows.find((row) => {
    const nome = isEncryptedText(row.nome) ? decrypt(row.nome) : row.nome;
    const cpf = isEncryptedText(row.cpf_cnpj)
      ? decrypt(row.cpf_cnpj)
      : row.cpf_cnpj;

    return (
      String(nome || "").trim().toLowerCase() ===
        nomeBalcao.toLowerCase() ||
      String(cpf || "").trim() === cpfBalcao
    );
  });

  if (clienteBalcao) {
    await pgm.db.query(
      `
      UPDATE clientes
      SET nome = $2,
          cpf_cnpj = $3,
          telefone = $4,
          endereco = $5,
          ativo = true,
          protegido = true
      WHERE id = $1
      `,
      [
        clienteBalcao.id,
        nomeBalcaoEnc,
        cpfBalcaoEnc,
        telefoneVazioEnc,
        enderecoVazioEnc,
      ],
    );
  } else {
    await pgm.db.query(
      `
      INSERT INTO clientes (id, nome, cpf_cnpj, telefone, endereco, ativo, criado_em, protegido)
      VALUES (gen_random_uuid(), $1, $2, $3, $4, true, now()::timestamp, true)
      `,
      [nomeBalcaoEnc, cpfBalcaoEnc, telefoneVazioEnc, enderecoVazioEnc],
    );
  }

  pgm.sql(`
    CREATE OR REPLACE FUNCTION fn_bloquear_cliente_protegido()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF OLD.protegido THEN
        RAISE EXCEPTION 'CLIENTE_PROTEGIDO_NAO_PODE_SER_ALTERADO';
      END IF;

      IF TG_OP = 'DELETE' THEN
        RETURN OLD;
      END IF;

      RETURN NEW;
    END;
    $$;
  `);

  pgm.sql(`
    DROP TRIGGER IF EXISTS trg_bloquear_cliente_protegido ON clientes;
    CREATE TRIGGER trg_bloquear_cliente_protegido
    BEFORE UPDATE OR DELETE ON clientes
    FOR EACH ROW
    EXECUTE FUNCTION fn_bloquear_cliente_protegido();
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS venda_itens (
      id text PRIMARY KEY,
      venda_id text NOT NULL REFERENCES vendas(id) ON DELETE CASCADE,
      insumo_id text NOT NULL REFERENCES insumos(id) ON DELETE RESTRICT,
      quantidade_kg numeric NOT NULL,
      quantidade_informada numeric NOT NULL,
      unidade_id integer NOT NULL REFERENCES aux_unidade(id) ON DELETE RESTRICT,
      kg_por_saco numeric,
      preco_unitario numeric NOT NULL,
      valor_total numeric NOT NULL,
      criado_em timestamp NOT NULL DEFAULT now()
    )
  `);

  pgm.sql(`
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS tipo_pagamento text NOT NULL DEFAULT 'A_VISTA';
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS forma_pagamento text;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS desconto_tipo text;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS desconto_valor numeric NOT NULL DEFAULT 0;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS desconto_descricao text;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS acrescimo_tipo text;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS acrescimo_valor numeric NOT NULL DEFAULT 0;
    ALTER TABLE vendas ADD COLUMN IF NOT EXISTS acrescimo_descricao text;
  `);

  pgm.sql(`
    ALTER TABLE transferencias
    ADD COLUMN IF NOT EXISTS unidade_operacao_id integer REFERENCES aux_unidade(id) ON DELETE RESTRICT;
    ALTER TABLE transferencias
    ADD COLUMN IF NOT EXISTS quantidade_informada numeric;
    ALTER TABLE transferencias
    ADD COLUMN IF NOT EXISTS kg_por_saco_informado numeric;
  `);

  pgm.sql(`
    DO $$
    DECLARE
      kg_id integer;
    BEGIN
      SELECT id INTO kg_id FROM aux_unidade WHERE codigo = 'KG' LIMIT 1;

      IF kg_id IS NOT NULL THEN
        UPDATE transferencias
        SET unidade_operacao_id = kg_id
        WHERE unidade_operacao_id IS NULL;
      END IF;

      UPDATE transferencias
      SET quantidade_informada = quantidade_kg
      WHERE quantidade_informada IS NULL;
    END $$;
  `);

  pgm.sql(`
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS valor_programado numeric;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS valor_recebido numeric;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS forma_recebimento_real text;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS motivo_diferenca text;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS acao_diferenca text;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS origem_recebimento text NOT NULL DEFAULT 'NORMAL';
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS fornecedor_destino_id uuid REFERENCES fornecedores(id) ON DELETE SET NULL;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS comprovante_url text;
    ALTER TABLE contas_receber_parcelas
    ADD COLUMN IF NOT EXISTS observacao_recebimento text;
  `);

  pgm.sql(`
    UPDATE contas_receber_parcelas
    SET valor_programado = valor
    WHERE valor_programado IS NULL
  `);

  pgm.sql(`
    ALTER TABLE contas_receber_parcelas
    ALTER COLUMN valor_programado SET NOT NULL
  `);

  pgm.sql(`
    CREATE TABLE IF NOT EXISTS aux_forma_pagamento (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo text NOT NULL UNIQUE,
      label text NOT NULL,
      ativo boolean NOT NULL DEFAULT true,
      criado_em timestamp NOT NULL DEFAULT now()
    )
  `);

  pgm.sql(`
    INSERT INTO aux_forma_pagamento (codigo, label)
    VALUES
      ('CHEQUE', 'Cheque'),
      ('TRANSFERENCIA', 'Transferência'),
      ('DINHEIRO', 'Dinheiro'),
      ('PIX', 'Pix'),
      ('CREDITO', 'Crédito'),
      ('DEBITO', 'Débito')
    ON CONFLICT (codigo) DO UPDATE SET label = EXCLUDED.label
  `);
};

exports.down = (pgm) => {
  pgm.sql("DROP TRIGGER IF EXISTS trg_bloquear_cliente_protegido ON clientes");
  pgm.sql("DROP FUNCTION IF EXISTS fn_bloquear_cliente_protegido() CASCADE");

  pgm.sql("DROP TABLE IF EXISTS venda_itens CASCADE");

  pgm.sql(`
    ALTER TABLE vendas
    DROP COLUMN IF EXISTS tipo_pagamento,
    DROP COLUMN IF EXISTS forma_pagamento,
    DROP COLUMN IF EXISTS desconto_tipo,
    DROP COLUMN IF EXISTS desconto_valor,
    DROP COLUMN IF EXISTS desconto_descricao,
    DROP COLUMN IF EXISTS acrescimo_tipo,
    DROP COLUMN IF EXISTS acrescimo_valor,
    DROP COLUMN IF EXISTS acrescimo_descricao
  `);

  pgm.sql(`
    ALTER TABLE transferencias
    DROP COLUMN IF EXISTS unidade_operacao_id,
    DROP COLUMN IF EXISTS quantidade_informada,
    DROP COLUMN IF EXISTS kg_por_saco_informado
  `);

  pgm.sql(`
    ALTER TABLE contas_receber_parcelas
    DROP COLUMN IF EXISTS valor_programado,
    DROP COLUMN IF EXISTS valor_recebido,
    DROP COLUMN IF EXISTS forma_recebimento_real,
    DROP COLUMN IF EXISTS motivo_diferenca,
    DROP COLUMN IF EXISTS acao_diferenca,
    DROP COLUMN IF EXISTS origem_recebimento,
    DROP COLUMN IF EXISTS fornecedor_destino_id,
    DROP COLUMN IF EXISTS comprovante_url,
    DROP COLUMN IF EXISTS observacao_recebimento
  `);

  pgm.sql("DROP TABLE IF EXISTS aux_forma_pagamento CASCADE");
  pgm.sql("DROP TABLE IF EXISTS aux_unidade CASCADE");
};
